### ISSUE TITLE
unsuport this type hints

### ISSUE THREAD

**Issue by zbh255** [mauricelambert/PyObfuscator#11]
`obfuscate.py`
```python
from PyObfuscator import Obfuscator


def constr():
    return str


class Model1(object):
    user_name: constr()


if __name__ == '__main__':
    Obfuscator('obfuscate.py', level=2, names_size=32, deobfuscate=False).default_obfuscation()

```
> I am not a professional python developer, Don't know how to describe it

**Comment by mauricelambert** [comment]
Thanks for opening this issue ! I have reproduce the error, i will fix it.

**Comment by mauricelambert** [comment]
I fix the bug here: [line with fix](https://github.com/mauricelambert/PyObfuscator/blob/1a9ec47577de43c563dc66992c221db476ac00ce/PyObfuscator.py#L1129) and a second bug with the same syntax here: [line with fix](https://github.com/mauricelambert/PyObfuscator/blob/1a9ec47577de43c563dc66992c221db476ac00ce/PyObfuscator.py#L1137).

Bugs come with annotations that is not a `Constant` and without assigned value. To fix it i check the python type and i add a default value to `None`.

You can update the package with pip, other package manager or with the source code from the repository and retry your obfuscation.

Thanks for the issue !
