### ISSUE TITLE
'ModuleNotFoundError: No module named' occurs

### ISSUE THREAD

**Issue by wookidooki8** [mauricelambert/PyObfuscator#2]
when trying to obfuscate, i get 'ModuleNotFoundError: No module named' error when trying to import a custom module by using
'from  ~ import *'. it doesnt seems to occur when you import them by using 'import'. is there 

![image](https://github.com/mauricelambert/PyObfuscator/assets/104318789/4533478f-d7cf-4245-9363-6fb08d5466a4)

for example, import driverx wont cause any errors but from driverx import * will do
any way to solve this?

**Comment by mauricelambert** [comment]
Thanks for your issues, i will try to reproduce this error and fix it.

If you want to help me to fix this issues you can write a code to generate this error and share me the full error message.

**Comment by mauricelambert** [comment]
I try to get your error but the following code raise no exception:

```python
import os
print(os.name)
from os import *
print(name)
```

I use the `import` and the `from ... import *` and i use it but i don't have any error, i need more information to fix the bug.

**Comment by mauricelambert** [comment]
You can try the latest version of `PyObfuscator` for your obfuscation, i don't think the new version fix this issue but i will work on the latest version to fix it.

**Comment by wendelgomesdev** [comment]
I'm encountering an issue when trying to import a module after applying obfuscation with Pyobfuscator. The error occurs when using the import with "*", which I would like to avoid, but it's necessary due to the constants present in the module.

Problem Description:
When importing the module with from extensions.blastzap.elements_compile import *, I receive the following error:

**Code:**
`from extensions.elements_compile import *`

**Error:**
`AttributeError: module 'extensions.elements_compile' has no attribute '__path__'. Did you mean: '__name__'?`

Importing these constants using '*' results in the error mentioned, but importing them explicitly works fine.

**Comment by mauricelambert** [comment]
Hi @wendelgomesdev, thanks for the issue.

I think it's normal because i exclude variables import when starts with `__` and ends with `__` to don't overwrite the main module builtin variables. I can probably fix that in your case by checking if the variable exists in the main module and exclude only if exists (the `__path__` variable is not a builtin variables so it should not exists in the main module). An other solution is to remove the exclusion because the error is an attribute error, so variable should not be written in the same namespace that main module builtin variables.

I will work on the issue and try to fix it with the good way.

**Comment by mauricelambert** [comment]
I have found the bug with the following test:

```python
from urllib.request import *
urlopen("http://example.com/")
```

```bash
python3 PyObfuscator.py -l 1 test.py
```

And i get the following code:

```python
... # some code here for initialization
ziyWOT1vA2Jk, stszrXMRGUWq, Uuc2hk8UGGnp, qJ_GSXaEr1Ql, ezMIo9Uw_Top = (bGqFsm7wyoJ6(bGqFsm7wyoJ6(cKGM5aGwIcq4('urllib.request', '__path__'), 'request'), '__path__'), bGqFsm7wyoJ6(bGqFsm7wyoJ6(cKGM5aGwIcq4('urllib.request', 'error'), 'request'), 'error'), bGqFsm7wyoJ6(bGqFsm7wyoJ6(cKGM5aGwIcq4('urllib.request', 'parse'), 'request'), 'parse'), bGqFsm7wyoJ6(bGqFsm7wyoJ6(cKGM5aGwIcq4('urllib.request', 'request'), 'request'), 'request'), bGqFsm7wyoJ6(bGqFsm7wyoJ6(cKGM5aGwIcq4('urllib.request', 'response'), 'request'), 'response'))
jHGv5ZZcxHhu('http://example.com/')
```

We can see the `__path__` is imported.

Now we can see the following code used to obfuscate `from ... import *`: [the line with bug](https://github.com/mauricelambert/PyObfuscator/blob/50c86fec75647fe9c2f4f25667bc22a0e6dcfeb0/PyObfuscator.py#L978)

```python
                for name in getattr(module, "__all__", dir(module))
```

So, i try to do the same in `pdb`:

```
(Pdb) import ast
(Pdb) print(ast.dump(astcode))
ImportFrom(module='urllib.request', names=[alias(name='__path__'), alias(name='error'), alias(name='parse'), alias(name='request'), alias(name='response')], level=0)
(Pdb) module
<module 'urllib' from 'C:\\Program Files\\Python\\Lib\\urllib\\__init__.py'>
(Pdb) dir(module)
['__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__path__', '__spec__', 'error', 'parse', 'request', 'response']
(Pdb) module.__path__
['C:\\Program Files\\Python\\Lib\\urllib']
(Pdb) from urllib.request import __path__
*** ImportError: cannot import name '__path__' from 'urllib.request' (C:\Program Files\Python\Lib\urllib\request.py)
(Pdb)
```

Module have a special attribute `__path__`, this attribute can be getted with `module.__path__` or `getattr(module, '__path__')` but cannot be imported. I try others specials attributes but there is no error on import:

```
(Pdb) from urllib.request import __builtins__
(Pdb) from urllib.request import __cached__
(Pdb) from urllib.request import __doc__
(Pdb) from urllib.request import __file__
(Pdb) from urllib.request import __loader__
(Pdb) from urllib.request import __name__
(Pdb) from urllib.request import __package__
(Pdb) from urllib.request import __path__
*** ImportError: cannot import name '__path__' from 'urllib.request' (C:\Program Files\Python\Lib\urllib\request.py)
(Pdb) from urllib.request import __spec__
```

There are good documentations for the `__path__` attribute, but i don't see any information about not importable attribute: [python documentation](https://docs.python.org/3/reference/import.html#path__), [PEP 420](https://peps.python.org/pep-0420/)
